---
- hosts: 172.31.26.183
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: copy myindexfile into ansible node side
    copy:
      src: myindexfile
      dest: /var/www/html/index.html
  - name: copy index j2 file into ansible node side
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: webserverrestart

  - name: i want to download remote(internet) file
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/
      force_basic_auth: yes
  handlers:
  - name: webserverrestart
    service: 
       name: apache2
       state: started
    